name: package-template

channels:
    - astropy

dependencies:
    - python=3.7*
    - astropy
    - Cython
    - matplotlib
    - numpy
    - scipy
    - sphinx
    - sphinx-astropy
#   - pip:
#       - dependency_from_pip