name: package-template

channels:
    - astropy

dependencies:
    - python=3.7*
    - astropy
    - matplotlib
    - numpy
    - scipy
    - sphinx
    - sphinx-astropy
    - sphinx-automodapi>=0.12
    - sphinx-gallery
    - pip:
       - sphinx-automodapi>=0.12